# Generated by Django 4.2.16 on 2024-11-17 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangopractise', '0002_sizedbook_alter_book_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyBook',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangopractise.book',),
        ),
    ]
