# Generated by Django 4.2.16 on 2024-11-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangopractise', '0003_proxybook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProxyBook',
        ),
        migrations.CreateModel(
            name='GoodBook',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangopractise.book',),
        ),
    ]
